Feature/mypage a pi
KIT-Frontend-Team2/Paradise pull request #88
Opened 2023-08-06 15:22 UTC by uniend

### 요약 (Summary)

- 마이페이지 api 연결 

### 바뀐 점 (Changes)

- 등록페이지 조회, 삭제 
- 관심페이지 조회,하트
- 최근페이지 조회
- 가계부 페이지 조회
- 계정관리 페이지 - 정보수정, 비번수정
- 프로필변경페이지 - 프로필 변경 

### 특이사항 (Optional)

-가계부페이지 조회시 null값과 제품정보가 넘어오지 않는다. 줍줍마켓과 네고마켓도 비슷 
- 상대방의 id를 넘겨야함 ** 

### Screenshots (Optional)

-

2023-08-06 16:55 UTC, Jihyeong00 requested changes

2023-08-06 16:55 UTC, Jihyeong00 commented on src/components/ui/organisms/MyPageSection/SellMenuBar.jsx
> +			alert('물품 삭제를 취소하셨습니다.')
물품 삭제를 취소하였는데 alert창을 띄워야할까요?

2023-08-06 16:55 UTC, Jihyeong00 commented on src/hooks/service/useMypage.service.js
> +			onError: () => {
`ERROR_MESSAGE` 로 API 에러가 일어날시에 해당 메세지를 띄울수 있도록 상수로 만들어 두었습니다.!

2023-08-07 09:02 UTC, Jihyeong00 commented on src/hooks/service/useMypage.service.js
> +	useCheckNicName: nickname => {
기존에 만들어져있는 함수가 있는데 왜 또 mutate로 만드신거죠?

2023-08-07 09:03 UTC, Jihyeong00 commented
> 삭제했던 /auth 브런치 커밋한 내용도 업로드 됐는데 괜찮을까여.. ?
불필요한 커밋내역은 최대한 줄여주세요

2023-08-07 12:49 UTC, uniend commented on src/hooks/service/useMypage.service.js
> +	useCheckNicName: nickname => {
변경했씁니다.

2023-08-07 12:50 UTC, uniend commented on src/components/ui/organisms/MyPageSection/SellMenuBar.jsx
> +			alert('물품 삭제를 취소하셨습니다.')
그부분 지웠습니다.

2023-08-07 12:50 UTC, uniend commented on src/components/ui/organisms/MyPageSection/MyPageInfo.jsx
> +		const UserInfo = {
data.키로 대체해서 해결했습니다.

2023-08-07 12:50 UTC, uniend commented on src/components/templates/MyPageTemplate/MyProfileTemplate.jsx
> +		console.log(formData.get('image'))
넵!

2023-08-07 12:53 UTC, uniend commented on src/hooks/service/useMypage.service.js
> +			onError: () => {
에러부분 지웠습니다.

2023-08-07 13:43 UTC, uniend commented on src/components/templates/MyPageTemplate/MyCashTemplate.jsx
> +	const nowDate = new Date()
사용했습니다.

2023-08-07 14:32 UTC, Jihyeong00 requested changes

2023-08-07 14:32 UTC, Jihyeong00 commented on src/components/templates/MyPageTemplate/MyProfileTemplate.jsx
> +						<img src={data.data.profile_url} alt={data.data.nick_name} />
이전에 구조분해 할당으로 잘 빼셨는데 왜 다시 바꾸신걸까요

2023-08-07 15:48 UTC, uniend commented on src/components/templates/MyPageTemplate/MyProfileTemplate.jsx
> +						<img src={data.data.profile_url} alt={data.data.nick_name} />
넵!

2023-08-07 16:17 UTC, uniend commented on src/hooks/service/useMypage.service.js
> +	useRecentPage: () => {
수정했어염

2023-08-09 08:04 UTC, Jihyeong00 commented on src/components/ui/organisms/MyPageSection/MyPageInfo.jsx
> +		const UserInfo = {
왜 watch를 사용해야 하는걸까요? 이미 적어놓은 닉네임을 그대로 가져가서 유효성 검사하는거 아닐까요~? 실시간으로 검사를 할 필요가 없습니다

2023-08-09 08:14 UTC, Jihyeong00 approved these changes
고생하셨습니다 :)

2023-08-09 13:44 UTC, merged